### ISSUE TITLE
Bot possibly dislikes nested curly braces

### ISSUE THREAD

**Issue by mirkoRainer** [TheCraiggers/Pathfinder-Discord-Bot#59]
Using this:
!omni set stat Chuck spellAttack:{{1d20}+T+WIS}
Caused the bot to show it was typing indefinitely. 
Need to test for this.

**Comment by coreyabrown** [comment]
This issue was likely fixed with the Refactor dice rolling changes.

**Comment by TheCraiggers** [comment]
Right you are! Thanks for noting that.

Fixed with #65
