### ISSUE TITLE
Custom Properties Do Not Allow Multiplication or Division

### ISSUE THREAD

**Issue by coreyabrown** [TheCraiggers/Pathfinder-Discord-Bot#64]
Consider changing the propertiesRegex to the line below to allow for multiplication and division when adding properties as well as parentheses. This would allow automatic rolling for critical hits i.e. criticalbowdamage:=2*({1d6}+{1d6})+{1d10}

In the example below, I added "|\*|\/|\(|\)" to the existing regex to allow the other characters that math.js should be able to handle. 

propertiesRegex = /(?<important>!)?(?<propertyName>\w+):((?<propertyMinValue>\d+)(\/|\\)(?<propertyMaxValue>\d+)|(?<propertyValue>(=?(\w|\[|\]|\{|\}|\+|-|\*|\/|\(|\))+)))/g;

**Comment by TheCraiggers** [comment]
Makes sense. I hate the way I did these Regexes. Ugh... these things were refactored so many times, this one probably fell through the cracks.

Anyway, just built a new computer, and my IDE isn't set up yet. It'll take me a couple days, but should be a very easy fix.

**Comment by coreyabrown** [comment]
Cool! I tried to fix it myself, but my computer is so crappy, I couldn't even install npm!!

**Comment by TheCraiggers** [comment]
I jinxed myself by calling this an easy fix.

Got it mostly working, but I'm currently stuck on PF2E's rule that you should always round down on fractions. The current way the math works is that all dice are rolled, and then the math is done. This will lead to very odd results for complex math.

I'll think on this some more. Worst case, I can always release with multiplication support as that's safe from this issue.

**Comment by coreyabrown** [comment]
That's true. Division would cause problems, but multiplication and parentheses should always result in whole numbers based on the possible inputs.

**Comment by coreyabrown** [comment]
Also, re-reading my proposed fix, it looks like the escape characters weren't saved in my copy paste! You'd likely add the following to the regex:

|\\*|(|)

You probably already knew that, just figured I would clarify!

**Comment by TheCraiggers** [comment]
I think I have a solution, but it'll require some refactoring. On the plus side, I'll be able to remove an entire dependency while also heavily increasing the amount of stuff the roller can do.
